available_locales: ["en"]
default_locale: "en"

user:
  maximum_fullname: 50
  maximum_email: 255
  minimum_pass: 8
  expire: 2
development:
  port: "587"
sessions:
  remember_me: "1"
football_new_per: 15
