available_locales: ["en"]
default_locale: "en"

user:
  maximum_fullname: 50
  maximum_email: 255
  minimum_pass: 8
  expire: 2
  min_length: 1
development:
  port: "587"
sessions:
  remember_me: "1"
football_new_per: 15
user_per: 15
league_per: 15
country_per: 15
team_per: 5
round_per: 5
gender: ["Male", "Female"]
league_number_min: 0
